# Generated by Django 4.1.1 on 2022-10-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_pago_fechayhora_pago_id_mes_pago_id_tipopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='detalle',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
