# Generated by Django 4.1.1 on 2022-10-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='detalle',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='rutina',
            name='cantidadMax',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rutina',
            name='cantidadMin',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rutina',
            name='id_categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rutina.categoria'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='id_ejercicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rutina.ejercicio'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='id_categoria',
            field=models.ManyToManyField(default=None, to='rutina.categoria'),
        ),
    ]
